# Numpy

Numpy é um pacote fundamental para computação numérica com Python.
Ele oferece poderosos caminhos para criar, armazenar e/ou manipular dados.


-Array Creation

-Attributes and Methods 

-Array Operations

-Indexing,Slicing and Iterating

-Trying Numpy with Datasets

In [1]:
import numpy as np

## Array Creation


### From a list 

In [83]:
#Arrays são exibidos como uma lista ou lista de listas e podem ser criados a partir de um lista.
a=np.array([1,2,3])
print(a)
#Podemos imprimir a dimensão de um array utilizando o atributo 'ndim'
print(a.ndim)
#Podemos checar o tipo dos itens dos arrays
a.dtype

[1 2 3]
1


dtype('int32')

In [84]:
#Se passarmos um lista de listas, estaremos criando um array multi-dimensional, ou seja, uma matriz.
b=np.array([[1,2,3],[4,5,6]])
print(b)
#Podemos imprimir o tamanho de cada dimensão(linha e coluna) utilizando o atributo 'shape', que retorna uma tupla
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

### arange

In [2]:
# Podemos criar uma sequência de números no array utilizando a funçãto 'arrange()'.O primeiro argumento é o começo
# do intervalo, o segundo argumento é o fim do intervalo e o terceiro é o passo.
f=np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

### linspace

In [126]:
#Para gerar uma sequência de floats, nós podemos utilizar a função 'linspace()'. O terceiro argumento não é o passo,
# mas sim o total de número que queremos gerar, igualmente espaçados.
np.linspace(0,2,15) #15 números igualmente espaçados de 0 a 2(incluso)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

### zeros and Ones

In [85]:
#As vezes nós sabemos o tamanho do array que queremos criar, mas não sabemos o que queremos colocar nas entradas.
# Numpy oferece algumas funções para criar arrays utlizando placeholders, como zeros ou uns
zero=np.zeros((2,3))
one=np.ones((2,3))
print(zero)
print(one)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


### eye

In [125]:
# Podemos criar uma matrix identidade
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
rand
randn
randint

In [127]:
# Podemos, também, gerar um array com números aleatórios de zero a um
random=np.random.rand(2,3)
random1D=np.random.rand(2)
print(random1D)
print(random)

[0.30665819 0.63841667]
[[0.33835147 0.00891247 0.59137433]
 [0.29925766 0.80641795 0.80389696]]


In [5]:
# Podemos criar um array com números de uma 'distribuição normal'
np.random.randn(5,5)

array([[-0.12497002,  0.87387003, -0.71703468,  0.29163515,  2.32280412],
       [ 0.84158397,  0.2701856 , -0.58602909,  0.43533612,  0.16138094],
       [-1.43297669,  0.44099347,  0.36376314, -0.51670044,  0.0884176 ],
       [ 0.11817942,  0.40208607, -0.6761538 ,  0.33578058,  1.24150553],
       [ 0.37562372,  0.5810359 ,  1.86800202, -0.66118811,  1.19657017]])

In [6]:
# randint(1,100) retorna um inteiro entre 1 a 100
# randint(1,100,10)retorna 10 inteiros entre 1 e 100
print(np.random.randint(1,100))
print(np.random.randint(1,100,10))

7
[ 9 91 99 53 18 91 87 95 99 61]


## Attributes and Methods 

In [7]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

### dtype 

In [157]:
arr.dtype

dtype('int32')

### Reshape

In [138]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
# É um vetor
arr.shape

(25,)

In [11]:
# É um vetor, ndim = 1
arr.reshape(25,) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [156]:
# É uma matrix, ndim=2
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [158]:
#Podemos ver o surgimento de um par de brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [16]:
arr=arr.reshape(5,5)

### max,min,argmax,argmin
argmax e argmin retornam a posição do maior ou menor elemento

In [141]:
ranarr

array([10, 19, 30, 29,  0, 24, 35, 35,  5, 18])

In [143]:
print(ranarr.max())
print(ranarr.min())
print(ranarr.argmax())
print(ranarr.argmin())

35
0
6
4


## Array Operations 

In [132]:
# Podemos fazer qualquer manipulação matemática entre os arrays e também manipulação matricial

In [90]:
#Operações aritméticas em um array são aplicadas elemento por elemento

#Vamos criar dois arrays
array1=np.array([10,30,50,70])
array2=np.array([1,2,3,4])

soma=array1+array2
subtração=array1-array2
divisao=array1/array2 # 0/0 retorna 'nan' e n/0 retorna 'inf'
multiplicação=array1*array2

print(soma)
print(subtração)
print(divisao)
print(multiplicação)

[11 32 53 74]
[ 9 28 47 66]
[10.         15.         16.66666667 17.5       ]
[ 10  60 150 280]


In [91]:
#Podemos fazer operações com arrays:
array3=(array1-31)/2
array3

array([-10.5,  -0.5,   9.5,  19.5])

In [92]:
#Operações matriciais
A_1D=np.array([1,2,3])
B_1D=np.array([4,5,6])

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

#Produto interno
innerProduct=np.inner(A_1D,B_1D)
print("inner Product:",innerProduct)

#Produto
dotProduct=np.dot(A,B)
print("dot Product:",dotProduct)

#Transposta
transposeMatrix=np.transpose(A)
print("transpose Matrix:",transposeMatrix)

#Traço
trace=A.trace()
print("trace",trace)

#Rank
rank=np.linalg.matrix_rank(A)
print("rank",rank)

#Determinante
det=np.linalg.det(A)
print("determinante:",det)

#Matriz inversa
inverseMatrix=np.linalg.det(A)
print("inverse Matrix:",inverseMatrix)



inner Product: 32
dot Product: [[5 4]
 [3 4]]
transpose Matrix: [[1 0]
 [1 1]]
trace 2
rank 2
determinante: 1.0
inverse Matrix: 1.0


In [93]:
#Autovalores e Autovetores

eigenvalues,eigenvectors=np.linalg.eig(A)
print("autovalores:",eigenvalues)
print("autovetores:",eigenvectors)

autovalores: [1. 1.]
autovetores: [[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


In [94]:
#Arrays possuem as funções sum(),max(),min() e mean()
print(array1.sum())
print(array1.max())
print(array1.min())
print(array1.mean())

#Para arrays mult

160
70
10
40.0


In [123]:
# Funções especiais do numpy
arr = np.arange(0,10)

print(np.sqrt(arr))
print(np.exp(arr)) # Calcula exp(valor)
print(np.sin(arr))
print(np.log(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\T-Gamer\AppData\Local\Temp/ipykernel_3952/3933080669.py:7: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


## Indexing, Slicing and Iterating 

###  Indexing

In [95]:
#Array 1D
a=np.array([1,2,3,4,5])
a[2]


3

In [96]:
# Para n-D arrays, precisamos passar 2 números
b=np.array([[1,2,3],[4,5,6]])
b[1,2]


6

In [160]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [165]:
# Podemos pegar as linhas ou colunas fora de ordem
b[[2,0]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

### Boolean Indexing


#### Boolean Mask


In [97]:
# Boolean indexing nos permite selecionar elementos arbitrários baseado em condições
b=np.array([[1,2,3],[4,5,6]])

b>2

array([[False, False,  True],
       [ True,  True,  True]])

In [98]:
# Podemos colocar esse array de booleanos como uma máscara sobre o array original retornando um array 1D contendo os valores que satisfazem a condição
b[b>2]

array([3, 4, 5, 6])

### Slicing 

In [99]:
#Slicing é um jeito de criar um subarray baseado no array original
#Se for um array 1D, utilizamos []
a=np.array([1,2,3,4,5])
a[:3]


array([1, 2, 3])

In [100]:
#Se for um array nD, utilizando [,]
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
#Se passarmos um argumento, esse argumento corresponderá à linha
b[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [102]:
#Se passarmos dois argumentos, esses argumentos corresponderão à (linha,coluna)
b[:2,1:3] 

array([[2, 3],
       [6, 7]])

In [103]:
#Um slice em um array é uma visão dos mesmos dados. Isso é chamado de valor de referência
#Ou seja, se alteramos um valor no sub_array, então o valor do array original também será alterado.

### Copy 

In [159]:
c=b.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Trying Numpy with Datasets

In [104]:
#Dataset sobre vinhos.
#Os campos incluem:fixed acidity, volatile aciditycitric acid, residual sugar, chlorides, free sulfur dioxide,
# total sulfur dioxidedensity, pH, sulphates, alcohol, quality


In [105]:
#Para carregar um dataset no Numpy, utilizamos a função genfromtxt().
#Nós podemos especificar o nome do arquivo, delimitador(opcional) e o número
# de linhas a serem puladas(caso tenhamos algum cabeçalho)

#Podemos passar também o parâmetro dtype especificando o tipo de dados.
#Sem especificar esse parâmetro, todosos dados serão moldados ao parâmetro mais geral do datasete
wines=np.genfromtxt("datasets/winequality-red.csv",delimiter=';',skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [106]:
#Podemos selecionar alguma coluna ou linha especificamente.

#Se quisermos, por exemplo, a coluna 0 que representa a "fixed acidity"
wines[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [107]:
#Se quisermos preservar o jeito que as colunas estão sendo mostradas, nós escrevermos
wines[:,0:1]

array([[7.4],
       [7.8],
       [7.8],
       ...,
       [6.3],
       [5.9],
       [6. ]])

In [108]:
#Podemos calcular a média da qualidade dos vinhos, selecionando a coluna correspondente
# à qualidade e calculando a sua média.
wines[:,-1].mean()

5.6360225140712945

In [109]:
#Dataset sobre graduação
#Campos: GRE score, TOEFL score, university rating,GPA, having research experience or not,
# and chance of admission.
# Podemos analisar quais condições são necessárias com a alta chance de admissão

In [110]:
# Nós podemos especificar os nomes das colunas utilizando o genfromtxt() para carregar arquivos CSV.
# Podemos também deixar o numpy tentar inferir o tipo da coluna setando o parâmetro 'dtype' para None
graduate_admission = np.genfromtxt('datasets/Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1,
                                   names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [111]:
# Podemos perceber que o resultado é,na verdade, um array unidimensional com 400 tuplas
graduate_admission.shape

(400,)

In [112]:
# Podemos pegar uma coluna utilizando o nome dela
graduate_admission['CGPA'][:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

In [113]:
# Podemos fazer um tratamento de dados na coluna CGPA
# Como GPA vai de 1 a 10, e nos EUA é mais comum a escala ser até 4, podemos converter os valores dividindo por 10 e multiplicando por 4
graduate_admission['CGPA'] = graduate_admission['CGPA'] /10 *4
graduate_admission['CGPA'][:5]

array([3.86 , 3.548, 3.2  , 3.468, 3.284])

In [114]:
# Podemos utilizar uma máscara booleana para descobrir quantos estudantes tem experiência em pesquisa.
len(graduate_admission[graduate_admission['Research']==1])

219

In [115]:
# Como temos o campo 'chance de admissão' que vai de 0 a 1 , podemos verse os estudantes com alta 
# chance de admissão (>0.8) tem média de GRE score maiores do que aqueles com baixa chance (<0.4)
print(graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['GRE_Score'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit'] < 0.4]['GRE_Score'].mean())

328.7350427350427
302.2857142857143


In [136]:
# Vamos fazer isso com o CGPA também
print(graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['CGPA'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit'] < 0.4]['CGPA'].mean())

3.7106666666666666
3.0222857142857142
