# Numpy

Numpy é um pacote fundamental para computação científica em Python. 

#### Numpy's features:
* **Vectorization**: A vetorialização descreve a ausência de loop explícito, indexação, etc. Com ela podemos executar operações matemáticas em matrizes inteiras, eliminando a necessidade de percorrer elementos individuais.
* **Broadcasting**: Termo usado para descrever o implícito comportamento elemento a elemento das operações. Ao multiplicar uma matriz por um escalar, o escalar é "esticado" para se tornar uma matriz da mesma forma que a matriz e a operação funcionar.


O coração do numpy é o objeto `ndarray`. Ele encapsula arrays n-dimensionais de tipos de dados homogêneos. Em numpy dimensões são chamadas de `axes` (eixos). Por exemplo, o array de coordenadas em um ponto 3D no espaço `[1,2,3]` tem um axis(eixo) e esse axis tem 3 elementos, ou seja, tem comprimento 3. No exemplo abaixo, o array tem 2 axis, o primeiro(linhas) tem comprimento 2 e o segundos axis(colunas) tem comprimento 3.

`[[1., 0., 0.],`
`[0., 1., 2.]]`

#### Some attributes

* **ndarray.ndim**: Número de axes (dimensões) do array;
* **ndarray.shape**: Tupla tupla de inteiros contendo o tamanho de cada dimensão. Portando, o comprimento da tupla é o número de axes;
* **ndarray.size**: Número total de elementos do array. É igual ao produto dos elementos do shape;
* **ndarray.dtpye**: Um objeto descrevendo os tipos de elementos do array;
* **ndarray.itemsize**: O tamanho em bytes de cada elemento do array
* **ndarray.data**: Buffer contendo os atuais elementos do array;



## Array Creation

Existem diferentes formas de criar um array

* **np.array()**: Cria um array a partir de uma lista ou tupla;
* **np.zeros()**: Cria um array de 0 a partir de uma tupla com 2 elementos representando o shape;
* **np.ones()**: Cria um array de 1 a partir de uma tupla com 2 elementos representando o shape;
* **np.empty()**: Cria um array com entradas aleatórias e depende do estado da memória a partir  de uma tupla com 2 elementos representando o shape;
* **np.arange()**: Cria um array com uma sequência de números.Pode ser passado um step;
* **np.linspace()**: Cria um array com uma sequência de números. Pode ser passado um intervalo;
* **np.eye()**: Cria uma matrix identidade;

Existem formas de criar um array a partir de outro array:

* **np.zeros_like()**: Retorna um novo array de 0's com o mesmo shape do array passado;
* **np.empty_like()**: Retorna um novo array com números aleatórios com o mesmo shape do array passado;
* **np.ones_like()**: Retorna um novo array de 1's com o mesmo shape do array passado; 

Criar array a partir de função:

* **np.fromfunction()**: Constrói um array ao executar uma função sobre cada coordenada;

Criar array a partir de um arquivo:

* **np.fromfile()**: Constrói um array a partir de dados em um arquivo de texto ou binário;


Criar array a partir do pacote **random**:

* **np.random.rand()**: Cria um array com números aleatórios de 0 a 1 a partir de uma tupla com 1,2 ou mais elementos;
* **np.random.randn()**: Cria um array  com números de uma distribuição normal a partir de uma tupla com 1,2 ou mais elementos;
* **np.random.randint()**: Cria um array  com números de uma distribuição normal a partir de uma tupla com 3 ou mais elementos;

### Exemplos:


In [16]:
import numpy as np
arraylist_a=np.array([1,2,3])
print(arraylist_a)

[1 2 3]


In [17]:
arraylist_b=np.array([[1,2,3],[4,5,6]])
print(arraylist_b)

[[1 2 3]
 [4 5 6]]


In [11]:
arrayarange=np.arange(10,50,3) # 3 aqui é como o step do range em python
print(arrayarange)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [12]:
arraylinspace=np.linspace(10,50,3) # 3 aqui é quantos números queremos
print(arraylinspace)

[10. 30. 50.]


In [32]:
arrayzeros=np.zeros((2,3))
arrayones=np.ones((2,3))
arrayempty=np.empty((2,3))

print(arrayzeros)
print("")
print(arrayones)
print("")
print(arrayempty)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [46]:
random1D=np.random.rand(3)
random2D=np.random.rand(2,3)
random3D=np.random.rand(2,3,4)
print(random1D)
print("")
print(random2D)
print("")
print(random3D)

[0.44707438 0.80981364 0.51508238]

[[0.94439081 0.85480468 0.55062985]
 [0.84489343 0.50319796 0.24566242]]

[[[0.95471119 0.88920188 0.49208987 0.69186922]
  [0.2131328  0.52833329 0.96403927 0.56849096]
  [0.6487533  0.18248994 0.24407571 0.98585341]]

 [[0.82042146 0.81031524 0.9408081  0.06664856]
  [0.24464869 0.0268391  0.35051536 0.45361355]
  [0.33670583 0.15621219 0.948799   0.42350703]]]


In [63]:
randomrandn=np.random.randn(5,5)
print(randomrandn)

[[ 0.51519898  1.49770873 -0.86096016 -1.62727519  1.85137916]
 [ 1.30469203  0.00794404  0.90018398  1.4985903  -1.15152629]
 [-0.75240816  1.34553724 -0.46278056 -1.9506792  -0.36653074]
 [-0.86955492 -0.21252899  0.58058568  0.82368604 -0.30389479]
 [-0.00870302 -0.97236704  1.60461253  1.49590973  1.31575251]]


In [69]:
randomrandint1D=np.random.randint(1,100) # Gera um número
randomrandint=np.random.randint(1,100,4) # Gera um array
print(randomrandint1D)
print(randomrandint)

51
[ 7 93 22 53]
