# Attributes and Methods

#### Some attributes

* **ndarray.ndim**: Número de axes (dimensões) do array;
* **ndarray.shape**: Tupla tupla de inteiros contendo o tamanho de cada dimensão. Portando, o comprimento da tupla é o número de axes;
* **ndarray.size**: Número total de elementos do array. É igual ao produto dos elementos do shape;
* **ndarray.dtpye**: Um objeto descrevendo os tipos de elementos do array;
* **ndarray.itemsize**: O tamanho em bytes de cada elemento do array
* **ndarray.data**: Buffer contendo os atuais elementos do array;

#### Some methods

* **ndarray.reshape()**: Refatora o shape do array;
* **ndarray.max()**: Retorna o maior elemento do array;
* **ndarray.min()**: Retorna o menor elemento do array;
* **ndarray.argmax()**: Retorna a posição do maior elemento do array;
* **ndarray.argmin()**: Retorna a posição do menor elemento do array;
* **ndarray.sum()**: Retorna a soma dos elementos do array;
* **ndarray.mean()**: Retorna a média dos elementos do array

In [38]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

## Exemplos atributos


**ndmin**

In [30]:
arraya.ndim

2

**shape**

In [31]:
array.shape

(3, 3)

**size**

In [32]:
array.size

9

**dtype**

In [34]:
array.dtype

dtype('int32')

**itemsize**

In [36]:
array.itemsize

4

**data**

In [37]:
array.data

## Exemplos métodos

**reshape()**

In [43]:
newarray=array.reshape(3,4)
newarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**max()**

In [45]:
array.max()

12

**min()**

In [46]:
array.min()

1

**argmax()**

In [47]:
array.argmax()

11

**argmin()**

In [49]:
array.argmin()

0

**sum()**

In [56]:
array.sum()

78

In [57]:
array.sum(axis=0) #columns

array([22, 26, 30])

In [58]:
array.sum(axis=1) #rows

array([ 6, 15, 24, 33])

**mean()**

In [53]:
array.mean()

6.5

In [59]:
array.mean(axis=0) #columns

array([5.5, 6.5, 7.5])

In [60]:
array.mean(axis=1) #rows

array([ 2.,  5.,  8., 11.])