# Array Operations

Operações aritméticas em array são aplicam *elementwise*. Um novo array é criado como resultado.

Operadores do tipo **+=** e ***=** modificam um array existente ao invés de criar um novo.

In [11]:
import numpy as np
a=np.array([[1, 1],
              [0, 1]])
b=np.array([[2, 0],
              [3, 4]])

**Subtração ou soma**

In [13]:
c=a+b
c

array([[3, 1],
       [3, 5]])

**Multiplicação**
Ao contrário de matrizes, o operador * opera *elementwise*.

In [14]:
b*2

array([[4, 0],
       [6, 8]])

**Produto Matricial**

In [15]:
a@b

array([[5, 4],
       [3, 4]])

**Potência**

In [23]:
b**2

array([0.       , 2.4674011, 9.8696044])

## I.Podemos fazer operações inteiras com arrays

In [24]:
array1=np.array([10,30,50,70])
array2=np.array([1,2,3,4])
array3=(array1-31)/2
array3


array([-10.5,  -0.5,   9.5,  19.5])

## II.Operações Matriciais

In [29]:
A_1D=np.array([1,2,3])
B_1D=np.array([4,5,6])

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

**Produto interno**

In [30]:
innerProduct=np.inner(A_1D,B_1D)
innerProduct

32

**Produto**

In [31]:
dotProduct=np.dot(A,B)
dotProduct2=A@B
print(dotProduct)
print(dotProduct2)

[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


**Transposta**

In [32]:
transposeMatrix=np.transpose(A)
transposeMatrix

array([[1, 0],
       [1, 1]])

**Traço**

In [34]:
trace=A.trace()
trace

2

**Rank**

In [36]:
rank=np.linalg.matrix_rank(A)
rank

2

**Determinante**

In [37]:
det=np.linalg.det(A)
det

1.0

**Matriz Inversa**

In [39]:
inverseMatrix=np.linalg.inv(A)
inverseMatrix

array([[ 1., -1.],
       [ 0.,  1.]])

**autovalores e autovetores**

In [41]:
eigenvalues,eigenvectors=np.linalg.eig(A)
print("autovalores:",eigenvalues)
print("autovetores:",eigenvectors)

autovalores: [1. 1.]
autovetores: [[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]
