# Indexing, Slicing and Iteranting

In [4]:
import numpy as np

## Indexing and Slicing

**Array 1D**

array[i]

## Indexing and Slicing

slicing faz shallow copy

In [7]:
a=np.array([1,2,3,4,5])

**Array 2D**

array[i,j]

In [9]:
b=np.array([[1,2,3],[4,5,6]])
b[0:2,2]

array([3, 6])

**Array 3D**

array[i,j,k]

In [23]:
c = np.array([[[  0,  1,  2],
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c[0,1:,0:]

array([[10, 12, 13]])

## Boolean Masking

Boolean masking nos permite selecionar elementos arbitrários baseados em condições.

In [24]:
booleanarray=np.array([[1,2,3],[4,5,6]])
b>2

array([[False, False,  True],
       [ True,  True,  True]])

**Podemos colocar esse array de booleanos como uma máscara sobre o array original.**

In [25]:
b[b>2]

array([3, 4, 5, 6])

## Iterating

In [26]:
iteratingarray=np.array([[1,2,3],[4,5,6]])

**rows**

In [27]:
for rows in iteratingarray:
    print(rows)

[1 2 3]
[4 5 6]


**elements**

In [28]:
for element in b.flat:
    print(element)

1
2
3
4
5
6
