# Trying numyp with Datasets

## Dataset sobre vinhos

Dataset sobre vinhos.  
Os campos incluem:  
`fixed acidity`  
`volatile aciditycitric acid`  
`residual sugar`  
`chlorides`  
`free sulfur dioxide`  
`total sulfur dioxidensity`  
`pH`  
`sulphates`  
`alchool`  
`quality`

Para carregar um dataset no Numpy, utilizamos o método `genfromtxt()`.  
Nós podemos especificar o nome do arquivo, delimitador, número de linhas a serem puladas e dtype.

In [3]:
import numpy as np

In [9]:
wines=np.genfromtxt("../datasets/winequality-red.csv",delimiter=";",skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

### Agora vamos aplicar algumas coisas que foram estudadas

Podemos selecionar alguma coluna ou linha especificamente.  
Se quisermos, por exemplo, a coluna 0 que representa o "fixed acidity".

In [10]:
wines[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

Podemos calcular a média da qualidade dos vinhos, selecionando a coluna correspondente e aplicando o método `mean`.

In [12]:
wines[:,-1].mean()

5.6360225140712945

## Data set sobre graduação

Dataset sobre graduação.  
Os campos incluem:  
`GRE score`  
`TOEFL scorte`  
`university rating`  
`GPA`  
`having research experience`  
`chance of admission`

Nós podemos especificar os nomes das colunas utilizando o parâmetro "names".

In [27]:
graduate_admission=np.genfromtxt('../datasets/Admission_Predict.csv'
                                 ,delimiter=','
                                 ,skip_header=1
                                ,names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))
graduate_admission

array([(  1., 337., 118., 4., 4.5, 4.5, 9.65, 1., 0.92),
       (  2., 324., 107., 4., 4. , 4.5, 8.87, 1., 0.76),
       (  3., 316., 104., 3., 3. , 3.5, 8.  , 1., 0.72),
       (  4., 322., 110., 3., 3.5, 2.5, 8.67, 1., 0.8 ),
       (  5., 314., 103., 2., 2. , 3. , 8.21, 0., 0.65),
       (  6., 330., 115., 5., 4.5, 3. , 9.34, 1., 0.9 ),
       (  7., 321., 109., 3., 3. , 4. , 8.2 , 1., 0.75),
       (  8., 308., 101., 2., 3. , 4. , 7.9 , 0., 0.68),
       (  9., 302., 102., 1., 2. , 1.5, 8.  , 0., 0.5 ),
       ( 10., 323., 108., 3., 3.5, 3. , 8.6 , 0., 0.45),
       ( 11., 325., 106., 3., 3.5, 4. , 8.4 , 1., 0.52),
       ( 12., 327., 111., 4., 4. , 4.5, 9.  , 1., 0.84),
       ( 13., 328., 112., 4., 4. , 4.5, 9.1 , 1., 0.78),
       ( 14., 307., 109., 3., 4. , 3. , 8.  , 1., 0.62),
       ( 15., 311., 104., 3., 3.5, 2. , 8.2 , 1., 0.61),
       ( 16., 314., 105., 3., 3.5, 2.5, 8.3 , 0., 0.54),
       ( 17., 317., 107., 3., 4. , 3. , 8.7 , 0., 0.66),
       ( 18., 319., 106., 3., 4

Podemos percerbe que o resultado é um array unidimensional com 400 elementos e, portanto, utilizar [:,0] para pegar uma coluna não funciona.

Podemos pegar uma coluna utilizando o nome dela.

In [28]:
graduate_admission['CGPA']

array([9.65, 8.87, 8.  , 8.67, 8.21, 9.34, 8.2 , 7.9 , 8.  , 8.6 , 8.4 ,
       9.  , 9.1 , 8.  , 8.2 , 8.3 , 8.7 , 8.  , 8.8 , 8.5 , 7.9 , 8.4 ,
       9.5 , 9.7 , 9.8 , 9.6 , 8.8 , 7.5 , 7.2 , 7.3 , 8.1 , 8.3 , 9.4 ,
       9.6 , 9.8 , 9.2 , 8.4 , 7.8 , 7.5 , 7.7 , 8.  , 8.2 , 8.5 , 9.1 ,
       9.4 , 9.1 , 9.3 , 9.7 , 8.85, 8.4 , 8.3 , 7.9 , 8.  , 8.1 , 8.  ,
       7.7 , 7.4 , 7.6 , 6.8 , 8.3 , 8.1 , 8.2 , 8.2 , 8.5 , 8.7 , 8.92,
       9.02, 8.64, 9.22, 9.16, 9.64, 9.76, 9.45, 9.04, 8.9 , 8.56, 8.72,
       8.22, 7.54, 7.36, 8.02, 9.5 , 9.22, 9.36, 9.45, 8.66, 8.42, 8.28,
       8.14, 8.76, 7.92, 7.66, 8.03, 7.88, 7.66, 7.84, 8.  , 8.96, 9.24,
       8.88, 8.46, 8.12, 8.25, 8.47, 9.05, 8.78, 9.18, 9.46, 9.38, 8.64,
       8.48, 8.68, 8.34, 8.56, 8.45, 9.04, 8.62, 7.46, 7.28, 8.84, 9.56,
       9.48, 8.36, 8.22, 8.47, 8.66, 9.32, 8.71, 9.1 , 9.35, 9.76, 8.65,
       8.56, 8.78, 9.28, 8.77, 8.45, 8.16, 9.08, 9.12, 9.15, 9.36, 9.44,
       9.92, 8.96, 8.64, 8.48, 9.11, 9.8 , 8.26, 9.

Podemos fazer um tratamento de dados na coluna GPA.  
Como o GPA vai de 1 a 10, e nos EUA é mais comum escalar até 4, podemos converter os valores.

In [29]:
graduate_admission['CGPA'] = graduate_admission['CGPA'] /10 *4
graduate_admission['CGPA'][:5]

array([3.86 , 3.548, 3.2  , 3.468, 3.284])

Podemos utilizar uma máscara boolean para descobrir quantos estudantes tem experiência em pesquisa.

In [30]:
len(graduate_admission[graduate_admission['Research']==1])

219

Podemos calcular a média do CGPA e do GRE score para os alunos que tem alta chance de admissão (>0.8) e baixa chance de admissão (<0.4).

In [40]:
print(graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['CGPA'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['CGPA'].mean())

3.7106666666666666
3.0222857142857142


In [41]:
print(graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['GRE_Score'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['GRE_Score'].mean())

328.7350427350427
302.2857142857143
